### ISSUE TITLE
Feature request: lightline support

### ISSUE THREAD

**Issue by oblitum** [AhmedAbdulrahman/aylin.vim#1]
Hi, thanks for this theme, it's really beautiful. I miss lightline support (like there's in [vim-deep-space](https://github.com/tyrannicaltoucan/vim-deep-space/tree/master/autoload) and [underword.vim](https://github.com/atchim/underworld.vim/tree/master/autoload) for example), it would be great to have.

**Comment by oblitum** [comment]
I think the cursor highlight on braces needs a little fix. I use block cursor, but on this colorscheme, when I hover over a brace, it looks like the cursor jumps to the ending brace, because the highlighting changes the current color of the cursor and makes a block highlighting at the ending pair, which end ups looking like a cursor jump.

**Comment by AhmedAbdulrahman** [comment]
Hi @oblitum I created a PR #2  for Lightline support will merge it so you can use it ;) . As for cursor on braces what kind of fix you mean?

**Comment by oblitum** [comment]
Hi @AhmedAbdulrahman, thanks for that, looks pretty nice, just tested.

As for the cursor issue, it's this:

![gif-2020-12-22-221427](https://user-images.githubusercontent.com/1269815/102947883-28374180-44a3-11eb-99f9-2ef572992f7f.gif)

**Comment by AhmedAbdulrahman** [comment]
I see then will fix that too and let you know :)

**Comment by AhmedAbdulrahman** [comment]
This should be fixed, can you confirm it?

**Comment by ewal** [comment]
Works for me :)
