### ISSUE TITLE
Errors reported when starting neovim

### ISSUE THREAD

**Issue by ewal** [AhmedAbdulrahman/aylin.vim#3]
First of all, I really love this theme. I get some errors though while starting neovim, using latest version 0.6.1.
Cheers.

Error detected while processing /Users/[***]/.dotfiles/.config/nvim/plugged/vim-aylin/colors/aylin.vim:
line  182:
E488: Trailing characters: # let colorgroup['BufferLineIndicatorSelected']   = {
line  183:
E488: Trailing characters: # let colorgroup['BufferLineFill']                = {
line  206:
E117: Unknown function: color_helper#hex_color_darken
line  207:
E117: Unknown function: color_helper#hex_color_darken
line  208:
E117: Unknown function: color_helper#hex_color_darken
line  209:
E117: Unknown function: color_helper#hex_color_darken
line  722:
E746: Function name does not match script file name: color_helper#hex_color_darken
line  735:
E746: Function name does not match script file name: color_helper#hex_color_to_rgb
line  739:
E746: Function name does not match script file name: color_helper#hex_to_dec
line  743:
E746: Function name does not match script file name: color_helper#dec_to_hex
line  752:
E746: Function name does not match script file name: color_helper#rgb_color_to_hex
.... plus some more.

**Comment by AhmedAbdulrahman** [comment]
Happy to hear that you love it @ewal  :) 

In which branch you get this error master or 0.5-nvim?

**Comment by ewal** [comment]
I'm using the master branch.

**Comment by AhmedAbdulrahman** [comment]
@ewal strange it should work as expected, are you using `Nvim Treesitter` ?

**Comment by ewal** [comment]
No, is Treesitter a requirement?. Using coc-nvim atm... I however found a couple of potential issues inside the colors/aylin.vim file:

https://github.com/AhmedAbdulrahman/aylin.vim/blob/master/colors/aylin.vim#L1
--> Vim(edit):E474: Invalid argument: fdm=marker"
This seems to be caused by the line ending with a double quotation mark. Error is gone after it's removed.

https://github.com/AhmedAbdulrahman/aylin.vim/blob/master/colors/aylin.vim#L182 (plus line 183)
These lines looks like they are intended to be out commented but with the incorrect symbol, `#` instead of `"`.

Errors still there though :)

**Comment by AhmedAbdulrahman** [comment]
I really appreciate it @ewal . I fixed the error you mentioned and the error that caused by helper functions. I should work now I pushed the fixed try to pull it and test :)

**Comment by AhmedAbdulrahman** [comment]
btw, Treesitter is not required! So keep using `master` branch. In case if you think of using Treesitter, then switch to 
`0.5-nvim` branch

**Comment by ewal** [comment]
All errors are gone after the update!  Thank you  🙏 Closing 🙂
