### ISSUE TITLE
What font are you using in the preview image?

### ISSUE THREAD

**Issue by Derpitron** [AhmedAbdulrahman/aylin.vim#5]
![image](https://user-images.githubusercontent.com/46134462/231750581-2719a4d6-45e8-4b0c-a543-4902eff8bb7a.png)

**Comment by AhmedAbdulrahman** [comment]
@Derpitron its `JetBrains Mono`
https://www.jetbrains.com/lp/mono/

**Comment by Derpitron** [comment]
It looks a bit different from JetBrains Mono. Have you changed any other font settings in this screenshot like kerning, tracking, etc?
